# Server Configuration
server:
  address: 192.168.0.103
  port: 8081

# Email server
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    auth: true
    starttls:
      enable: true
    username: ${MAIL_SMTP_USERNAME}
    password: ${MAIL_SMTP_PASSWORD}

spring:
  # Apache Kafka Config
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest

  # Receipts generator
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/uni_applications?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/db.master.xml
    drop-first: false
    liquibase-schema: liquibase

  # Security Configuration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://uni-application.ddns.net/auth/realms/${KEYCLOAK_REALM}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: https://uni-application.ddns.net/auth/realms/${KEYCLOAK_REALM}

  # Caching config
  cache:
    jcache:
      config: classpath:config/ehcache.xml
  data:
    redis:
      host: localhost
      port: 6379

# Hibernate Configuration
jpa:
  database-platform: org.hibernate.dialect.SQLServerDialect
  hibernate:
    ddl-auto: update

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cache: DEBUG
    org.hibernate.SQL: DEBUG
    root: INFO
    io:
      swagger: DEBUG

keycloak:
  auth-server-url: https://uni-application.ddns.net/auth
  realm: ${KEYCLOAK_REALM}
  resource: spring-realm
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET}

# Swagger config
springdoc:
  api-docs:
    enabled: true
