# Server Configuration
server:
  port: 8081

# Email server
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    auth: true
    starttls:
      enable: true
    username: ddanov100@gmail.com
    password: lkxxynplzjgdsifi

spring:
  # Apache Kafka Config
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      group-id: my-group-id

  # Receipts generator
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/uni_applications?serverTimezone=UTC&useSSL=false
    username: root
    password: weather-app23
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/db.master.xml
    drop-first: false
    liquibase-schema: liquibase

  # Security Configuration
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/SpringRealm
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringRealm

  # Caching config
  cache:
    jcache:
      config: classpath:config/ehcache.xml
  data:
    redis:
      host: localhost
      port: 6379

# Hibernate Configuration
jpa:
  database-platform: org.hibernate.dialect.SQLServerDialect
  hibernate:
    ddl-auto: update

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cache: DEBUG
    org.hibernate.SQL: DEBUG
    root: INFO
    io:
      swagger: DEBUG

keycloak:
  auth-server-url: http://localhost:8080
  realm: SpringRealm
  resource: spring-realm
  credentials:
    secret: ToJVr5ieDJBLFfxjU2dOCdPGpmbvpYBa

# Swagger config
springdoc:
  api-docs:
    enabled: true

# Mocking payments Spring boot App
mock:
  payment:
    url: "http://localhost:8083"